{% set name = "esp-tools" %}
{% set version = environ.get('GIT_DESCRIBE_TAG', 'untagged')|string|replace('-','_') %}
{% set build_number = environ.get('GIT_DESCRIBE_NUMBER', '0') %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  git_url: {{ environ.get('FEEDSTOCK_ROOT', '..') }}

build:
  number: {{ build_number }}
  string: {{ [build_number, ('h' + PKG_HASH), environ.get('GIT_DESCRIBE_HASH', '')]|join('_') }}
  skip: True # [not linux64]
  # needed to avoid overlinking errors
  missing_dso_whitelist:
    - '*'
  # needed to avoid unable to find specs files errors
  detect_binary_files_with_prefix: False
  # list out areas where conda can use patchelf (ignore the sysroot)
  binary_relocation:
    - 'esp-tools/bin/**'
    - 'esp-tools/include/**'
    - 'esp-tools/lib/**'
    - 'esp-tools/libexec/**'
    - 'esp-tools/riscv64-unknown-elf/**'
    - 'esp-tools/riscv64-unknown-linux-gnu/**'
    - 'esp-tools/share/**'

requirements:
  # only build section used since we are building on linux-64 a package intended to work on linux-64
  # host isn't needed since target-platform isn't another architecture
  build:
    # the {{ compiler(...) }} jinja macros don't pick up system includes so explicitly use the compilers
    - gcc>=10
    - gxx>=10
    - conda-gcc-specs

    - sysroot_linux-64 2.17 # [linux64]

    # if building riscv-toolchain from source, we need to use bison==3.4.* until we have
    # https://github.com/riscv-collab/riscv-binutils-gdb/commit/314ec7aeeb1b2e68f0d8fb9990f2335f475a6e33
    - bison==3.4.* # note: doing =3.4 doesn't work

    - make
    - autoconf
    - automake
    - texinfo
    - patch

    - gawk
    - git
    - dtc
    - binutils
    - flex
    - libtool
    - file

    # packages also in host and/or run
    - gmp
    - mpfr
    - mpc
    - expat
    - ncurses
    - zlib
    - python

  run:
    - expat
    - mpfr
    - ncurses
    - zlib
    - python # python_abi needed for riscv...gdb features

test:
  commands:
    - test "$($PREFIX/esp-tools/bin/riscv64-unknown-elf-gcc -dumpversion)" = "9.2.0"
    - riscv64-unknown-elf-ld --version
    - riscv64-unknown-elf-gdb --version

about:
  home: https://github.com/ucb-bar/esp-tools-feedstock
  summary: RISC-V toolchain for Hwacha/Gemmini UC Berkeley projects

extra:
  recipe-maintainers:
    - abejgonzalez
