{% set name = "ucb-bar-esp-tools" %}
{% set version = "9.2.0" %}
{% set build_number = environ.get('GIT_DESCRIBE_NUMBER', '0') %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - folder: src
    git_url: https://github.com/ucb-bar/ucb-bar-esp-tools.git
    git_rev: 4562650125c4889624bc56504c1816e61f6eaa35

build:
  number: {{ build_number }}
  string: {{ [build_number, ('h' + PKG_HASH), environ.get('GIT_DESCRIBE_HASH', '')]|join('_') }}
  skip: True # [not linux64]
  # needed to avoid overlinking errors
  missing_dso_whitelist:
    - '*'

requirements:
  build:
    # toolchain deps
    - gcc==10.*
    - gxx==10.*
    - conda-gcc-specs
    - gawk
    # if building riscv-toolchain from source, we need to use bison=3.4 until we have
    # https://github.com/riscv-collab/riscv-binutils-gdb/commit/314ec7aeeb1b2e68f0d8fb9990f2335f475a6e33
    - bison==3.4.*
    - patch
    - git
    - make
    - dtc
    - binutils
    - texinfo
    - python
    - autoconf
    - automake
    - flex
    - libtool
    # qemu specific
    - gtk3
    - pkg-config
    # qemu also requires being built against kernel-headers >= 2.6.38 because of it's use of
    # MADV_NOHUGEPAGE in a call to madvise.  See:
    # https://man7.org/linux/man-pages/man2/madvise.2.html
    # https://conda-forge.org/docs/maintainer/knowledge_base.html#using-centos-7
    # obvi this would need to be made linux-specific if we supported other MacOS or Windows
    - sysroot_linux-64 2.17 #[linux64]
  host:
    - expat
    - ncurses
    - gmp
    - mpfr
    - mpc
    - zlib
    # qemu specific
    - glib
    - pixman
    - zstd
    - libcurl

test:
  commands:
    - test "$($PREFIX/esp-tools/bin/riscv64-unknown-elf-gcc -dumpversion)" = "$PKG_VERSION"

about:
  home: https://github.com/ucb-bar/ucb-bar-esp-tools

extra:
  recipe-maintainers:
    - abejgonzalez
